<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1kxevfc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1kxevfc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1kxevfc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1kxevfc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1kxevfc\appDevDebugProjectContainer(array(
    'container.build_hash' => '1kxevfc',
    'container.build_id' => '6cb89ddb',
    'container.build_time' => 1517621601,
));
