<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS8zexng\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS8zexng/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerS8zexng.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerS8zexng\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerS8zexng\appDevDebugProjectContainer(array(
    'container.build_hash' => 'S8zexng',
    'container.build_id' => 'e5a1e7f5',
    'container.build_time' => 1518645695,
));
