<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJjcraxo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJjcraxo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJjcraxo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJjcraxo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJjcraxo\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jjcraxo',
    'container.build_id' => '50bda29b',
    'container.build_time' => 1521136690,
));
